# Generated by Django 6.0.3 on 2026-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomidor', '0002_project_tag_task_delete_pomidor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='uniq_task_title_in_project'),
        ),
    ]
